<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8004" started-at="2021-03-13T12:44:29 EST" finished-at="2021-03-13T12:44:37 EST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8004" started-at="2021-03-13T12:44:29 EST" finished-at="2021-03-13T12:44:37 EST">
      <class name="MyJob.JobChallenge.InvalidInput">
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="setupMethod" is-config="true" duration-ms="3693" started-at="2021-03-13T12:44:29 EST" finished-at="2021-03-13T12:44:33 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="PASS" signature="inputLetters()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="inputLetters" duration-ms="255" started-at="2021-03-13T12:44:33 EST" finished-at="2021-03-13T12:44:33 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inputLetters -->
        <test-method status="PASS" signature="teardownMethod()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="teardownMethod" is-config="true" duration-ms="599" started-at="2021-03-13T12:44:33 EST" finished-at="2021-03-13T12:44:34 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownMethod -->
        <test-method status="PASS" signature="setupMethod()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="setupMethod" is-config="true" duration-ms="2535" started-at="2021-03-13T12:44:34 EST" finished-at="2021-03-13T12:44:36 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupMethod -->
        <test-method status="FAIL" signature="inputNegative()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="inputNegative" duration-ms="240" started-at="2021-03-13T12:44:36 EST" finished-at="2021-03-13T12:44:37 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [[] = []] but found [[1] = [4]]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [[] = []] but found [[1] = [4]]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyJob.JobChallenge.InvalidInput.inputNegative(InvalidInput.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inputNegative -->
        <test-method status="PASS" signature="teardownMethod()[pri:0, instance:MyJob.JobChallenge.InvalidInput@5e25a92e]" name="teardownMethod" is-config="true" duration-ms="639" started-at="2021-03-13T12:44:37 EST" finished-at="2021-03-13T12:44:37 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardownMethod -->
      </class> <!-- MyJob.JobChallenge.InvalidInput -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
